version: '3.8'

services:
  ldap:
    image: osixia/openldap:1.1.7
  web:
    container_name: 925r-web
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8888:8000"
    depends_on:
      - ldap
